language: python
python:
- "3.8"
- "3.8-dev"  # 3.8 development branch
matrix:
  allow_failures:
  - python: 3.8-dev
services:
- docker
sudo: required
env:
- DOCKER_COMPOSE_VERSION=1.25.5
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
install:
- pip install pipenv
- pipenv install
script:
- coverage run src/manage.py test
- flake8 src
- docker-compose up --build -d dev
- docker-compose start dev
- docker-compose run dev npm test -- --watchAll=false
after_success:
- coveralls