version: "3.4"

x-common-variables: &common-variables
  POSTGRES_DB: linguagem-simples
  POSTGRES_USER: root
  POSTGRES_PASSWORD: linguagem-simples

services:
  db:
    container_name: linguagem-simples-db
    image: postgres
    restart: on-failure
    environment:
      <<: *common-variables
      PGDATA: "/var/lib/postgresql/data/"
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    container_name: linguagem-simples-backend
    build: .
    command: ./start_backend.sh
    restart: on-failure
    environment:
      <<: *common-variables
      SECRET_KEY: "key"
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      HOST: "db"
      PORT: 5432
      DATABASE_ENGINE: "postgresql"
      WATCHMAN_TOKEN_NAME: "token"
      WATCHMAN_TOKES: "key"
      API_DITEC: "http://localhost:8000"
    volumes:
      - .:/var/labhacker/linguagem_simples_backend
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg_data:
    driver: local
